In [1]:
import sys
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

from src.utils import get_processed_data_dir

In [2]:
from src.basket import (
    create_basket_matrix,
    find_frequent_itemsets,
    generate_association_rules
)

Load:

In [3]:
sales = pd.read_csv(
    get_processed_data_dir()
    / "online_retail_sales.csv",
    parse_dates=["InvoiceDate"]
)

/var/folders/ns/ms3xw2y52nj8x7n_3w_qw4tm0000gn/T/ipykernel_60501/4138439645.py:1: DtypeWarning: Columns (0: Invoice) have mixed types. Specify dtype option on import or set low_memory=False.
  sales = pd.read_csv(

Create basket:

In [4]:
basket = create_basket_matrix(
    sales
)

print(
    basket.shape
)

/Users/karthikeyanj/Desktop/projects/E-Commerce-Life-Cycle-Analysis/src/basket.py:32: Pandas4Warning: Using a fill_value that cannot be held in the existing dtype is deprecated and will raise in a future version.
  .pivot_table(

(20953, 4251)

Find itemsets:

In [5]:
itemsets = find_frequent_itemsets(
    basket,
    min_support=0.01
)

itemsets.sort_values(
    "support",
    ascending=False
).head(20)

      support             itemsets
691  0.156589  frozenset({85123A})
408  0.096359   frozenset({22423})
688  0.093829  frozenset({85099B})
92   0.088436   frozenset({21212})
98   0.078270   frozenset({21232})
25   0.073450   frozenset({20725})
649  0.067389   frozenset({84879})
663  0.063762   frozenset({84991})
195  0.063523   frozenset({21754})
37   0.056412   frozenset({20914})
243  0.056269   frozenset({21931})
62   0.056221   frozenset({21080})
254  0.055123   frozenset({21977})
398  0.054837   frozenset({22383})
308  0.054312   frozenset({22139})
27   0.053214   frozenset({20727})
613  0.053119  frozenset({82494L})
425  0.052117   frozenset({22470})
196  0.052069   frozenset({21755})
56   0.051258   frozenset({21034})

## Association Rules

In [6]:
rules = generate_association_rules(
    itemsets,
    min_confidence=0.2
)

Sort by lift:

In [7]:
rules.sort_values(
    "lift",
    ascending=False
).head(20)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
671,frozenset({22521}),frozenset({22520}),0.012838,0.012218,0.010166,0.791822,64.808739,1.0,0.010009,4.744882,0.997375,0.682692,0.789247,0.811926
670,frozenset({22520}),frozenset({22521}),0.012218,0.012838,0.010166,0.832031,64.808739,1.0,0.010009,5.877056,0.996748,0.682692,0.829847,0.811926
726,frozenset({22746}),frozenset({22745}),0.012456,0.015177,0.010691,0.858238,56.549218,1.0,0.010502,6.946996,0.994707,0.630986,0.856053,0.781320
727,frozenset({22745}),frozenset({22746}),0.015177,0.012456,0.010691,0.704403,56.549218,1.0,0.010502,3.340839,0.997454,0.630986,0.700674,0.781320
731,frozenset({22748}),frozenset({22746}),0.016322,0.012456,0.011168,0.684211,54.928211,1.0,0.010965,3.127221,0.998085,0.634146,0.680227,0.790381
730,frozenset({22746}),frozenset({22748}),0.012456,0.016322,0.011168,0.896552,54.928211,1.0,0.010965,9.508885,0.994178,0.634146,0.894835,0.790381
728,frozenset({22748}),frozenset({22745}),0.016322,0.015177,0.013077,0.801170,52.789014,1.0,0.012829,4.953081,0.997335,0.709845,0.798105,0.831402
729,frozenset({22745}),frozenset({22748}),0.015177,0.016322,0.013077,0.861635,52.789014,1.0,0.012829,7.109307,0.996175,0.709845,0.859339,0.831402
718,frozenset({22698}),frozenset({22697}),0.012838,0.017993,0.011120,0.866171,48.140268,1.0,0.010889,7.337777,0.991962,0.564165,0.863719,0.742104
719,frozenset({22697}),frozenset({22698}),0.017993,0.012838,0.011120,0.618037,48.140268,1.0,0.010889,2.584444,0.997169,0.564165,0.613070,0.742104
722,frozenset({22698}),frozenset({22699}),0.012838,0.018852,0.010213,0.795539,42.199821,1.0,0.009971,4.798707,0.989000,0.475556,0.791611,0.668656
723,frozenset({22699}),frozenset({22698}),0.018852,0.012838,0.010213,0.541772,42.199821,1.0,0.009971,2.154303,0.995062,0.475556,0.535813,0.668656
426,frozenset({21901}),frozenset({21902}),0.018756,0.012981,0.010166,0.541985,41.750758,1.0,0.009922,2.154991,0.994705,0.471239,0.535961,0.662536
427,frozenset({21902}),frozenset({21901}),0.012981,0.018756,0.010166,0.783088,41.750758,1.0,0.009922,4.523700,0.988885,0.471239,0.778942,0.662536
721,frozenset({22697}),frozenset({22699}),0.017993,0.018852,0.014079,0.782493,41.507806,1.0,0.013740,4.510889,0.993789,0.618449,0.778314,0.764664
720,frozenset({22699}),frozenset({22697}),0.018852,0.017993,0.014079,0.746835,41.507806,1.0,0.013740,3.878929,0.994659,0.618449,0.742197,0.764664
725,frozenset({22727}),frozenset({22726}),0.017038,0.016561,0.011025,0.647059,39.071538,1.0,0.010743,2.786411,0.991296,0.488372,0.641115,0.656382
724,frozenset({22726}),frozenset({22727}),0.016561,0.017038,0.011025,0.665706,39.071538,1.0,0.010743,2.940412,0.990815,0.488372,0.659912,0.656382
1145,"frozenset({21239, 21238})",frozenset({21240}),0.013220,0.021620,0.010834,0.819495,37.904790,1.0,0.010548,5.420226,0.986662,0.451292,0.815506,0.660299
1146,frozenset({21240}),"frozenset({21239, 21238})",0.021620,0.013220,0.010834,0.501104,37.904790,1.0,0.010548,1.977926,0.995133,0.451292,0.494420,0.660299

Filter useful rules:

In [8]:
useful_rules = rules[
    (rules["lift"] > 1)
    &
    (rules["confidence"] >= 0.3)
].sort_values(
    "lift",
    ascending=False
)

useful_rules.head(20)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
671,frozenset({22521}),frozenset({22520}),0.012838,0.012218,0.010166,0.791822,64.808739,1.0,0.010009,4.744882,0.997375,0.682692,0.789247,0.811926
670,frozenset({22520}),frozenset({22521}),0.012218,0.012838,0.010166,0.832031,64.808739,1.0,0.010009,5.877056,0.996748,0.682692,0.829847,0.811926
726,frozenset({22746}),frozenset({22745}),0.012456,0.015177,0.010691,0.858238,56.549218,1.0,0.010502,6.946996,0.994707,0.630986,0.856053,0.781320
727,frozenset({22745}),frozenset({22746}),0.015177,0.012456,0.010691,0.704403,56.549218,1.0,0.010502,3.340839,0.997454,0.630986,0.700674,0.781320
731,frozenset({22748}),frozenset({22746}),0.016322,0.012456,0.011168,0.684211,54.928211,1.0,0.010965,3.127221,0.998085,0.634146,0.680227,0.790381
730,frozenset({22746}),frozenset({22748}),0.012456,0.016322,0.011168,0.896552,54.928211,1.0,0.010965,9.508885,0.994178,0.634146,0.894835,0.790381
728,frozenset({22748}),frozenset({22745}),0.016322,0.015177,0.013077,0.801170,52.789014,1.0,0.012829,4.953081,0.997335,0.709845,0.798105,0.831402
729,frozenset({22745}),frozenset({22748}),0.015177,0.016322,0.013077,0.861635,52.789014,1.0,0.012829,7.109307,0.996175,0.709845,0.859339,0.831402
719,frozenset({22697}),frozenset({22698}),0.017993,0.012838,0.011120,0.618037,48.140268,1.0,0.010889,2.584444,0.997169,0.564165,0.613070,0.742104
718,frozenset({22698}),frozenset({22697}),0.012838,0.017993,0.011120,0.866171,48.140268,1.0,0.010889,7.337777,0.991962,0.564165,0.863719,0.742104
722,frozenset({22698}),frozenset({22699}),0.012838,0.018852,0.010213,0.795539,42.199821,1.0,0.009971,4.798707,0.989000,0.475556,0.791611,0.668656
723,frozenset({22699}),frozenset({22698}),0.018852,0.012838,0.010213,0.541772,42.199821,1.0,0.009971,2.154303,0.995062,0.475556,0.535813,0.668656
426,frozenset({21901}),frozenset({21902}),0.018756,0.012981,0.010166,0.541985,41.750758,1.0,0.009922,2.154991,0.994705,0.471239,0.535961,0.662536
427,frozenset({21902}),frozenset({21901}),0.012981,0.018756,0.010166,0.783088,41.750758,1.0,0.009922,4.523700,0.988885,0.471239,0.778942,0.662536
720,frozenset({22699}),frozenset({22697}),0.018852,0.017993,0.014079,0.746835,41.507806,1.0,0.013740,3.878929,0.994659,0.618449,0.742197,0.764664
721,frozenset({22697}),frozenset({22699}),0.017993,0.018852,0.014079,0.782493,41.507806,1.0,0.013740,4.510889,0.993789,0.618449,0.778314,0.764664
725,frozenset({22727}),frozenset({22726}),0.017038,0.016561,0.011025,0.647059,39.071538,1.0,0.010743,2.786411,0.991296,0.488372,0.641115,0.656382
724,frozenset({22726}),frozenset({22727}),0.016561,0.017038,0.011025,0.665706,39.071538,1.0,0.010743,2.940412,0.990815,0.488372,0.659912,0.656382
1145,"frozenset({21239, 21238})",frozenset({21240}),0.013220,0.021620,0.010834,0.819495,37.904790,1.0,0.010548,5.420226,0.986662,0.451292,0.815506,0.660299
1146,frozenset({21240}),"frozenset({21239, 21238})",0.021620,0.013220,0.010834,0.501104,37.904790,1.0,0.010548,1.977926,0.995133,0.451292,0.494420,0.660299